/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type LancamentoComissao = "ajuste" | "credito" | "estorno" | "saque";

export type MetodoPagamento = "cartao" | "pix";

export type Numeric = ColumnType<string, number | string, number | string>;

export type OrigemAtribuicao = "casa" | "cupom" | "link" | "rep_inativo";

export type PagamentoStatus = "aprovado" | "cancelado" | "em_analise" | "estornado" | "pendente" | "recusado";

export type PedidoStatus = "aguardando_pagamento" | "cancelado" | "em_preparacao" | "entregue" | "enviado" | "pago" | "pendente" | "reembolsado";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type TipoDesconto = "fixo" | "percentual";

export interface Clientes {
  atualizado_em: Generated<Timestamp>;
  cpf: string;
  criado_em: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  nome: string;
  whatsapp: string;
}

export interface Comissoes {
  criado_em: Generated<Timestamp>;
  descricao: Generated<string>;
  disponivel_em: Timestamp;
  id: Generated<string>;
  pedido_id: string | null;
  representante_id: string;
  tipo: LancamentoComissao;
  valor_centavos: number;
}

export interface CupomUsos {
  cliente_id: string;
  criado_em: Generated<Timestamp>;
  cupom_id: string;
  id: Generated<string>;
  pedido_id: string;
}

export interface Cupons {
  ativo: Generated<boolean>;
  codigo: string;
  criado_em: Generated<Timestamp>;
  expira_em: Timestamp | null;
  id: Generated<string>;
  inicia_em: Generated<Timestamp>;
  limite_por_cliente: Generated<number>;
  limite_total: number | null;
  representante_id: string | null;
  tipo: TipoDesconto;
  valor: number;
}

export interface Enderecos {
  bairro: string;
  cep: string;
  cidade: string;
  cliente_id: string;
  complemento: Generated<string>;
  criado_em: Generated<Timestamp>;
  estado: string;
  id: Generated<string>;
  numero: string;
  rua: string;
}

export interface Kits {
  anvisa_registro: string | null;
  ativo: Generated<boolean>;
  atualizado_em: Generated<Timestamp>;
  criado_em: Generated<Timestamp>;
  descricao: Generated<string>;
  id: Generated<string>;
  nome: string;
  ordem: Generated<number>;
  preco_centavos: number;
  sku: string;
  slug: string;
  unidades: number;
}

export interface Pagamentos {
  atualizado_em: Generated<Timestamp>;
  criado_em: Generated<Timestamp>;
  id: Generated<string>;
  metodo: MetodoPagamento;
  parcelas: Generated<number>;
  pedido_id: string;
  provedor: Generated<string>;
  provedor_id: string | null;
  status: Generated<PagamentoStatus>;
  valor_centavos: number;
}

export interface PedidoItens {
  criado_em: Generated<Timestamp>;
  id: Generated<string>;
  kit_id: string;
  nome_snapshot: string;
  pedido_id: string;
  preco_unitario_centavos: number;
  quantidade: number;
  total_centavos: number;
}

export interface Pedidos {
  cliente_id: string | null;
  criado_em: Generated<Timestamp>;
  cupom_id: string | null;
  desconto_centavos: Generated<number>;
  endereco_id: string | null;
  entregue_em: Timestamp | null;
  frete_centavos: Generated<number>;
  id: Generated<string>;
  numero: Generated<Int8>;
  origem: OrigemAtribuicao;
  pago_em: Timestamp | null;
  percentual_comissao_snapshot: Numeric | null;
  representante_id: string | null;
  status: Generated<PedidoStatus>;
  subtotal_centavos: number;
  token: Generated<string>;
  total_centavos: number;
  utm_campaign: string | null;
  utm_medium: string | null;
  utm_source: string | null;
}

export interface Pgmigrations {
  id: Generated<number>;
  name: string;
  run_on: Timestamp;
}

export interface Representantes {
  ativo: Generated<boolean>;
  atualizado_em: Generated<Timestamp>;
  cidade: Generated<string>;
  codigo: string;
  criado_em: Generated<Timestamp>;
  email: string;
  estado: Generated<string>;
  foto_url: string | null;
  id: Generated<string>;
  nome: string;
  percentual_comissao: Generated<Numeric>;
  slug: string;
  whatsapp: Generated<string>;
}

export interface WebhookEventos {
  evento_id: string;
  id: Generated<string>;
  payload: Json;
  processado_em: Timestamp | null;
  provedor: Generated<string>;
  recebido_em: Generated<Timestamp>;
  recurso_id: string | null;
  tipo: string;
}

export interface DB {
  clientes: Clientes;
  comissoes: Comissoes;
  cupom_usos: CupomUsos;
  cupons: Cupons;
  enderecos: Enderecos;
  kits: Kits;
  pagamentos: Pagamentos;
  pedido_itens: PedidoItens;
  pedidos: Pedidos;
  pgmigrations: Pgmigrations;
  representantes: Representantes;
  webhook_eventos: WebhookEventos;
}
