/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Kits {
  anvisa_registro: string | null;
  ativo: Generated<boolean>;
  atualizado_em: Generated<Timestamp>;
  criado_em: Generated<Timestamp>;
  descricao: Generated<string>;
  id: Generated<string>;
  nome: string;
  ordem: Generated<number>;
  preco_centavos: number;
  sku: string;
  slug: string;
  unidades: number;
}

export interface Pgmigrations {
  id: Generated<number>;
  name: string;
  run_on: Timestamp;
}

export interface DB {
  kits: Kits;
  pgmigrations: Pgmigrations;
}
